name: john mordomo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60204
title: John Mordomo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#beb688'
    - '#f7ebaf'
    - '#6c6d72'
    - '#2b3346'
    - '#000228'
  brandStrength: 0.8125
  lightness: 0.5687579826917499
  saturation: 0.9097595605999231
  rhythmicContrast: 0
purpose: []
